language: generic

dist: xenial

matrix:
  include:
    - os: linux
      env: CXX="g++-7" CC="gcc-7"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libboost-program-options-dev
            - libboost-system-dev
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX="g++-8" CC="gcc-8"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-program-options-dev
            - libboost-system-dev
          sources: *sources
    - os: linux
      env: CXX="clang++-6.0" CC="clang-6.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-8
            - cmake
            - libboost-program-options-dev
            - libboost-system-dev
          sources:
            - llvm-toolchain-xenial-6.0
            - ubuntu-toolchain-r-test
script:
  - cmake --version
  - cmake .
  - make -j 2
  - ctest .
